BaseURl = https://cipherdevui.azurewebsites.net
mailId = testing.team_iat@ilink-systems.com
Password = Testacc:8910


giftStoreUrl = https://cipherdevui.azurewebsites.net/giftstore
excelFilepath = /testData/testdata.xlsx
excelSheetName = Sheet1

###################################################
############CheerUp Buddy##########################




cheerUpBuddyExcelSheetName = CheerUpBuddy
CheerUpBuddySendBadgeFormExcelSheetName = CheerUpBuddySendBadgeForm
EmailIdNotMatch = Employee email does not match any record.
MissingFields = Employee email and comments are required.




########################################
#############Earn################
earnExcelSheetName = Earn






