package CipherplusAPI.BaseService;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.parsing.Parser;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import static io.restassured.RestAssured.given;

public class BaseService {



    public static final String BASE_URL = "https://cipherdev.azurewebsites.net";
    RequestSpecification requestSpecification;

    public BaseService() {
        RestAssured.defaultParser = Parser.JSON;
        requestSpecification  = given().baseUri(BASE_URL);
    }


//
    public Response getRequest(String endpoint){
        return requestSpecification.contentType(ContentType.JSON)
                .header("Authorization", "Bearer " + "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSIsImtpZCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSJ9.eyJhdWQiOiJhNzczZDZmYy1mZjVjLTRkNjQtOTQxMi1jNWE0Y2YyNmQ2OTkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hOGU1ZDU3MS00M2U4LTRjM2MtOTZiZS0zNDQxNTZjZjY4ODcvIiwiaWF0IjoxNzQyMzY2MDM0LCJuYmYiOjE3NDIzNjYwMzQsImV4cCI6MTc0MjM2OTkzNCwiYWlvIjoiQVZRQXEvOFpBQUFBejArTEZUZjUvTEw3YXdobk5VSHdqazhlWHQ4b3kxQ015RGxrOVVkMS8wQjRhKzFSQ28xeU1rUEZlaW9FYU44QVlFd1BrUEpseTJqdEIzc245N2l1OHR1a1FycFFPRjIraThsVlZTRm9Gakk9IiwiYW1yIjpbInB3ZCJdLCJjYyI6IkNtQTFkN3ZqaDlKR3VKZVMwVDdwbUhJejdpVHZ5c3V3MnBBdWpNOUg3MmozNytFT1kxdHlBaXZzR1ZUUEU1c04rTS9WbWlKbnFwUkNaY1RPb2hNVGo4dWNCc3Y4NTJlOUJxVnBYbXVZeGdNLy9QalZzVmJ0a0tIYTJ1UnROZkU0OUdzU0VXbHNhVzVyTFhONWMzUmxiWE11WTI5dEdoSUtFSW1sNFpjUW1zcExndUNHRkVBSTBNVWlFZ29RYWt6T3dWZVRBMGFreHBCaUFxY0ZBRElDVGtFNEFVSUpDWURCQ21Wc1VkMUlTZ2tKZ0VGdlhmOW8zVWc9IiwiZmFtaWx5X25hbWUiOiJUZWFtX0lBVCIsImdpdmVuX25hbWUiOiJUZXN0aW5nIiwiaXBhZGRyIjoiMTExLjkzLjEwOC41MCIsIm5hbWUiOiJUZXN0aW5nIFRlYW1fSUFUIiwibm9uY2UiOiI3NjkwMjEyOS1lYmZiLTQ1MmYtYmUzMi1mYzE1ODUwMmM5ZWIiLCJvaWQiOiI0N2I2MDcwMS01YjE3LTQ2NjgtOWQ0Mi1mMmQxNTYzZWZmZmUiLCJwd2RfZXhwIjoiMjUzNjgwIiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCIsInJoIjoiMS5BUklBY2RYbHFPaERQRXlXdmpSQlZzOW9oX3pXYzZkY18yUk5sQkxGcE04bTFwbldBTVVTQUEuIiwicm9sZXMiOlsiQWRtaW4iXSwic2lkIjoiMDAzMGI0ZDktNGI4NS0yOTcxLWI1ZTAtNDc4ZDZkODk3ZDM5Iiwic3ViIjoiOVhBa2JqVS1EU0JDT0tSUkF3OTFySmllenEyT3FUTFJQZi1ER19lR0dNbyIsInRpZCI6ImE4ZTVkNTcxLTQzZTgtNGMzYy05NmJlLTM0NDE1NmNmNjg4NyIsInVuaXF1ZV9uYW1lIjoidGVzdGluZy50ZWFtX2lhdEBpbGluay1zeXN0ZW1zLmNvbSIsInVwbiI6InRlc3RpbmcudGVhbV9pYXRAaWxpbmstc3lzdGVtcy5jb20iLCJ1dGkiOiJha3pPd1ZlVEEwYWt4cEJpQXFjRkFBIiwidmVyIjoiMS4wIn0.LiHo6d5z0EEE_LYS9AS1vCURqE_dPQ0awilDXVzx89FWFn-L2yiVFE9uJQA6iCWnjioNFieZgH1u7xDQmVY6rqPGpBMYfIw66U-x5ZzotHsZcov_EC03z0iHsdYh--aDeGVbF67zqvQwunqudJZdxeUzh_ytadm_sFeDeQRIIgK-TbLgweJfHl0MvWXCA6irEK7zBZv2GAeuHxAqvWjLOTRm6ysIC6KhfK1NnuRpnxX6BeXTE6ESIcDMEkpRaROV1TlRZ3pHQ1EoJP-h8ReOSMY4cOUQ1xuEudlERi5IVKz0zCYi5VP-QE5ktR-WSCyYvXsXApQuc9iCWhVg_s6oug") // Replace with a valid token or remove it

                .get(endpoint);
    }






}
