package CipherplusAPI.BaseService;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.parsing.Parser;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import static io.restassured.RestAssured.given;

public class BaseService {



    public static final String BASE_URL = "https://cipherdev.azurewebsites.net";
    RequestSpecification requestSpecification;

    public BaseService() {
        RestAssured.defaultParser = Parser.JSON;
        requestSpecification  = given().baseUri(BASE_URL);
    }



    public Response getRequest(String endpoint){
        return requestSpecification.contentType(ContentType.JSON)
                .header("Authorization", "Bearer " + "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSIsImtpZCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSJ9.eyJhdWQiOiJhNzczZDZmYy1mZjVjLTRkNjQtOTQxMi1jNWE0Y2YyNmQ2OTkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hOGU1ZDU3MS00M2U4LTRjM2MtOTZiZS0zNDQxNTZjZjY4ODcvIiwiaWF0IjoxNzQ0MDE2MDgxLCJuYmYiOjE3NDQwMTYwODEsImV4cCI6MTc0NDAxOTk4MSwiYWlvIjoiQVZRQXEvOFpBQUFBT0pDU3pwTHB3R1hLYkk2ZXZSYmtydmtKUVEvUXE4NjEwWjY2ZXp0Rm5VbUV4MmZuSG96VTNveFlVa0ZxNzlqNk5sa1k4WEZGUGVVd0dwMmRtbUFRUGU2RFYxNEo1ZVZpUkJ4U0JNZFEyNk09IiwiYW1yIjpbInB3ZCJdLCJmYW1pbHlfbmFtZSI6IlRlYW1fSUFUIiwiZ2l2ZW5fbmFtZSI6IlRlc3RpbmciLCJpcGFkZHIiOiIxMTEuOTMuMTA4LjUwIiwibmFtZSI6IlRlc3RpbmcgVGVhbV9JQVQiLCJub25jZSI6ImVhNzhhMTQwLWVlYmEtNDQ4MS1iMjM5LWI4YmEyNjAxMjQxYiIsIm9pZCI6IjQ3YjYwNzAxLTViMTctNDY2OC05ZDQyLWYyZDE1NjNlZmZmZSIsInJoIjoiMS5BUklBY2RYbHFPaERQRXlXdmpSQlZzOW9oX3pXYzZkY18yUk5sQkxGcE04bTFwbldBTVVTQUEuIiwicm9sZXMiOlsiU3VwZXJBZG1pbiJdLCJzaWQiOiIwMDNlMjI1OS01MzYwLTU5YmYtZjZiNC02MTFhYjU4NzY4YmQiLCJzdWIiOiI5WEFrYmpVLURTQkNPS1JSQXc5MXJKaWV6cTJPcVRMUlBmLURHX2VHR01vIiwidGlkIjoiYThlNWQ1NzEtNDNlOC00YzNjLTk2YmUtMzQ0MTU2Y2Y2ODg3IiwidW5pcXVlX25hbWUiOiJ0ZXN0aW5nLnRlYW1faWF0QGlsaW5rLXN5c3RlbXMuY29tIiwidXBuIjoidGVzdGluZy50ZWFtX2lhdEBpbGluay1zeXN0ZW1zLmNvbSIsInV0aSI6ImhpblJDM0JlRFVhNFh2dDNIWlk2QUEiLCJ2ZXIiOiIxLjAifQ.Sqp79NL1p8LQ0SnKYd6DN711zVh5xPJuW732WnuCKxHb2wiEEJrpvDmKYg0FYAT0pySajy7iwySwFb406HdNFP5b_ePpmteSpIPzy_xhbRndfD5mmp7RLwGTYB7BjM09aCuMuEcuxMdfak01u-J_vw-1AGXVd1u3m-UIY0BMVI1o3MnDpkmGxrIUaVbiYNVgD5rNu7POR08J8mIbeJyWF-_mk3LVLIpH-jSet5Ycf_uLgkKetNGakhXlVJHhb6YvcSp7zHSay9M7bmd3SNR_s4sWUXNYgccJfvaIxMsXNEZ_zDMh9lskTZFnHFhOaRhcthTsDJo1s_x735f8wj8zig") // Replace with a valid token or remove it
                .get(endpoint);
    }






}
