package CipherplusAPI.BaseService;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.parsing.Parser;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import static io.restassured.RestAssured.given;

public class BaseService {



    public static final String BASE_URL = "https://cipherdev.azurewebsites.net";
    RequestSpecification requestSpecification;

    public BaseService() {
        RestAssured.defaultParser = Parser.JSON;
        requestSpecification  = given().baseUri(BASE_URL);
    }



    public Response getRequest(String endpoint){
        return requestSpecification.contentType(ContentType.JSON)
                .header("Authorization", "Bearer " + "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSIsImtpZCI6IkNOdjBPSTNSd3FsSEZFVm5hb01Bc2hDSDJYRSJ9.eyJhdWQiOiJhNzczZDZmYy1mZjVjLTRkNjQtOTQxMi1jNWE0Y2YyNmQ2OTkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hOGU1ZDU3MS00M2U4LTRjM2MtOTZiZS0zNDQxNTZjZjY4ODcvIiwiaWF0IjoxNzQzNjU2MjU5LCJuYmYiOjE3NDM2NTYyNTksImV4cCI6MTc0MzY2MDE1OSwiYWlvIjoiQVZRQXEvOFpBQUFBK3AzWFF6dmp0OTNSNTh0SXQ3YStOdkl4T3ZjTm90U1pOTk5wVzZucEd2R0RvUEF4bnFBMlk3QU42NW1BRCtQRyt2RHVxa1RDYSt6aHZLYUpEV1N4dmJ5OWhiOXZBSmx4MkJwcnFPU3ZuSHc9IiwiYW1yIjpbInB3ZCJdLCJjYyI6IkNtQzNHSGl2SC8wTXVwVEdxUXVHa3dXekY2UkJwK1dvR3Q3WFNUb3N1d1FQQnE0YTVpOHIwdDRCckxSdnQwZ2RnK3g1V0Q0MWFYYzhVSXVCSnMzWExFYjhXQS9HWDFuWkc4M1RsdUFPZmxyQU9PZDZIN3d1NEhzcGtkN0R4OVBYWnZ3U0VXbHNhVzVyTFhONWMzUmxiWE11WTI5dEdoSUtFTm9XUTBVTWlOdEN2RHBmMHJqOUFWOGlFZ29RcVAwWGFuOVRyRWk1cEFIVTZJZ1lBRElDVGtFNEFVSUpDWURTdWwrY2F0MUlTZ2tKZ0ZJZldDK0MzVWc9IiwiZmFtaWx5X25hbWUiOiJUZWFtX0lBVCIsImdpdmVuX25hbWUiOiJUZXN0aW5nIiwiaXBhZGRyIjoiMTExLjkzLjEwOC41MCIsIm5hbWUiOiJUZXN0aW5nIFRlYW1fSUFUIiwibm9uY2UiOiJhNzQ0ZmIwZi00MDk5LTQ4MTgtOWY1Yy1hYmM0NzY5YmM4ZmUiLCJvaWQiOiI0N2I2MDcwMS01YjE3LTQ2NjgtOWQ0Mi1mMmQxNTYzZWZmZmUiLCJyaCI6IjEuQVJJQWNkWGxxT2hEUEV5V3ZqUkJWczlvaF96V2M2ZGNfMlJObEJMRnBNOG0xcG5XQU1VU0FBLiIsInJvbGVzIjpbIkFkbWluIl0sInNpZCI6IjAwM2Q4NjE5LWJiYWItYmRmMy1lNDE1LTM5ZTE2YTBmYmQyNSIsInN1YiI6IjlYQWtialUtRFNCQ09LUlJBdzkxckppZXpxMk9xVExSUGYtREdfZUdHTW8iLCJ0aWQiOiJhOGU1ZDU3MS00M2U4LTRjM2MtOTZiZS0zNDQxNTZjZjY4ODciLCJ1bmlxdWVfbmFtZSI6InRlc3RpbmcudGVhbV9pYXRAaWxpbmstc3lzdGVtcy5jb20iLCJ1cG4iOiJ0ZXN0aW5nLnRlYW1faWF0QGlsaW5rLXN5c3RlbXMuY29tIiwidXRpIjoicVAwWGFuOVRyRWk1cEFIVTZJZ1lBQSIsInZlciI6IjEuMCJ9.WVfLDdzTC70J_3JgYt2qXDQv1bGJyuHwvsSfz7pCLXM9XSXyWwFHkMLIqQlCCnmyOQUCXBojDBn8n5fZksNfu_Myn9sl9LEbU-LV-RQXmnxL2i9Z5lyb_ajYa57J-OMz0VWLINl0wHBDkTFYRXPiCgN3Y1pmT9bDNOLo45x7xdc_ulPziFR-DOok9BZfNQBYxIXx13C1vB3bavmEdbLngAq2zPg9J4kLXEqIsyBRsAKnvKpgUG9g0aWlGgCGtK7ZoQ1DY0bnUO0ZFnBeLqc9nBFnEiM50AfMJAJQtwigtkHgVZtuokmF32pNWqcUDl7N1nmx4AcvXZRfX_e0oypHOQ") // Replace with a valid token or remove it

                .get(endpoint);
    }






}
